<a href="https://colab.research.google.com/github/Paresh935/AML-Lab/blob/main/AML_ASSIGNMENTI2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Activity 1 : Create Arrays
import numpy as np

a = np.array([10,20,30,40])
print(a)

b = np.arange(3,11)
print(b)

c = np.linspace(0,1,5)
print(c)

[10 20 30 40]
[ 3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#Activity 2 : Matrix operation
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A+B)
print(A-B)
print(A*B)
print(A@B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
#Assignment 1 : take weather data of last 1 month of udupi and find which is hottest day and coldest day and then calculate the average temperature of that month and find which all dates above 35 degree
import numpy as np

# Sample dates for the last 30 days (e.g., July 5 to August 3, 2026)
dates = np.array([
    '2026-07-05', '2026-07-06', '2026-07-07', '2026-07-08', '2026-07-09',
    '2026-07-10', '2026-07-11', '2026-07-12', '2026-07-13', '2026-07-14',
    '2026-07-15', '2026-07-16', '2026-07-17', '2026-07-18', '2026-07-19',
    '2026-07-20', '2026-07-21', '2026-07-22', '2026-07-23', '2026-07-24',
    '2026-07-25', '2026-07-26', '2026-07-27', '2026-07-28', '2026-07-29',
    '2026-07-30', '2026-07-31', '2026-08-01', '2026-08-02', '2026-08-03'
])

# Corresponding recorded temperatures in Celsius for Udupi
temperatures = np.array([
    35.2, 36.1, 34.5, 33.8, 32.4, 31.0, 30.5, 35.8, 36.5, 33.2,
    32.9, 34.1, 35.0, 36.2, 33.5, 31.8, 30.9, 32.1, 33.0, 34.2,
    35.5, 36.0, 33.9, 32.5, 31.2, 30.8, 34.0, 35.1, 33.4, 32.0
])

# 1. Find the index of hottest and coldest day
hottest_index = np.argmax(temperatures)
coldest_index = np.argmin(temperatures)

hottest_date = dates[hottest_index]
hottest_temp = temperatures[hottest_index]

coldest_date = dates[coldest_index]
coldest_temp = temperatures[coldest_index]

# 2. Calculate the average temperature of the month
average_temp = np.mean(temperatures)

# 3. Find all dates with temperature above 35
above_35_mark = temperatures > 35.0
above_35_dates = dates[above_35_mark]


print(f"Hottest Day: {hottest_date} with {hottest_temp}°C")
print(f"Coldest Day: {coldest_date} with {coldest_temp}°C")
print(f"Monthly average temperature: {average_temp}°C")
print(f"Dates with temperature above 35: {above_35_dates}")

Hottest Day: 2026-07-13 with 36.5°C
Coldest Day: 2026-07-11 with 30.5°C
Monthly average temperature: 33.57°C
Dates with temperature above 35: ['2026-07-05' '2026-07-06' '2026-07-12' '2026-07-13' '2026-07-18'
 '2026-07-25' '2026-07-26' '2026-08-01']
